---
version: '3.9'
services:
  haqq-node:
    container_name: haqq-node
    image: ${IMAGE}
    environment:
    - KEY=<key name>
    - KEY_PASS=<insert password>
    - CHAINID=haqq_54211-3
    - MONIKER=<moniker name>
    - KEYRING=file
    - KEYALGO=eth_secp256k1
    - LOGLEVEL=info
    - CONFIG_PATH=/root/.haqqd
    ports:
    - '26656:26656'
    - '26657:26657'
    - '26660:26660'
    volumes:
    - /opt/haqq:/root/.haqqd
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: '14gb'
    restart: unless-stopped
