---
version: '3.9'
services:
  lava-node:
    container_name: lava-node
    image: ${IMAGE}
    environment:
    - KEY=lava_impulse
    - CHAINID=lava-testnet-1
    - MONIKER=LavaImpulse
    - KEYRING=test
    - KEYALGO=eth_secp256k1
    - LOGLEVEL=info
    - CONFIG_PATH=/root/.lava
    ports:
    - '26656:26656'
    - '26660:26660'
    volumes:
    - /opt/lava:/root/.lava
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: unless-stopped
